### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [duryagin/Class#1]
1. Код по заданию является такой же частью продукта, как и имя, так что его тоже стоит хранить в классе `Product`.
1. В `changePrice` и `rename` незачем явно удалять элемент из `Map`, `put` его перезапишет.
1. Только в методе `name` Вы проверяете, что элемента нет в `Map`, в остальных методах Вы этого не делаете. Явно проверять, кстати, не обязательно, можно просто проверить результат метода `get`.
1. Методам, изменяющим прейскурант, стоит как-то сигнализировать о наличии/отсутствии элемента, который изменяется. Например, если вместо добавления элемента происходит перезапись старого.
1. У Вас странный тест на `rename`.

**Comment by maximpetrov** [comment]
1. В `addProduct` нет смысла передавать код, он уже есть в `product`.
1. Нет необходимости явно проверять наличие элемента с помощью `containsKey`, можно просто проанализировать результат методов, которые вы используете после этого.

**Comment by maximpetrov** [comment]
И ещё я забыл, что в задании явно указано, что цена в рублях и копейках, а не просто `double`.

**Comment by duryagin** [comment]
1. Код больше не передается.
2. Не совсем понимаю, как нужно проанализировать результат методов без испоьзования containsKey.

Добавлен класс Price, теперь цена в рублях и копейках.

**Comment by maximpetrov** [comment]
1. Раз переопределили `equals()` для класса `Price`, то переопределите и `hashCode()`.
1. При суммировании Вы не учитываете копейки, так как делите нацело на 100 и всегда получаете 0.
1. Методы `get`, `put` и т.п. иногда возвращают `null`. На основании этого можно сделать вывод о том, есть (или был) объект в `Map` или нет.

**Comment by duryagin** [comment]
Есть исправления.

**Comment by maximpetrov** [comment]
1. Лучше в `addProduct` использовать `putIfAbsent`, чтобы не перетирать существующий продукт.
1. Вместо того, чтобы 2 раза вызывать `get`, сохраните результат в переменную.
1. `remove` тоже вызывать два раза не стоит, там это и смысла не имеет.

**Comment by duryagin** [comment]
Новые исправления.
